# services:
#   application:
#     #env_file: "services/app.env"

#     #restart: always

#     build:
#       context: .
#       dockerfile: services/Dockerfile

#     volumes:
#       - "/services/"

#     ports:
#       - "443:5000"

# version: '3'

services:
  api:
    build:
      context: .
      dockerfile: services/Dockerfile
      # command: gunicorn app:app -p eye_seg_app.pid -b 0.0.0.0:5000 -D
    volumes:
      - "/services/"
    #   - static_volume:/store/staticfiles/
    #   - media_volume:/store/mediafiles/
    expose:
      - 80

  nginx:
    build:
      context: .
      dockerfile: services/etc/nginx/Dockerfile
    ports:
      - 443:80
    # volumes:
    #   - static_volume:/store/staticfiles/
    #   - media_volume:/store/mediafiles/
# volumes:
#   static_volume:
#   media_volume: