# services:
#   application:
#     #env_file: "services/app.env"

#     #restart: always

#     build:
#       context: .
#       dockerfile: services/Dockerfile

#     volumes:
#       - "/services/"

#     ports:
#       - "443:5000"

# version: '3'

services:
  web_app:
    build:
      context: .
      dockerfile: services/Dockerfile
      # command: gunicorn app:app -p eye_seg_app.pid -b 0.0.0.0:5000 -D
    # volumes:
    #   - "/api/"
    #   - static_volume:/store/staticfiles/
    #   - media_volume:/store/mediafiles/
    # ports:
    #   - "443:5000"
    expose:
     - 5000

  nginx:
    build:
      context: .
      dockerfile: services/etc/nginx/Dockerfile
    ports:
      - "443:80"
    volumes:
      - /services/etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /services/etc/nginx/sites-available/reverse-proxy.conf:/etc/nginx/sites-available/reverse-proxy.conf
    #   - "/nginx/"
    #   - static_volume:/store/staticfiles/
    #   - media_volume:/store/mediafiles/
# volumes:
#   static_volume:
#   media_volume: