services:
  # frontend:
  #   image: nginx
  #   restart: always
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - "/services/ressources/"
  #   networks:
  #   - front-tier
  #   - back-tier
  #   configs:
  #     - httpd-config
  #   secrets:
  #     - server-certificate

  application:
    restart: always
    build:
      context: services
      dockerfile: Dockerfile
    volumes:
      - "services/ressources/backend/"
    ports:
    - "127.0.0.1:5000:5000"