services:
  application:
    #restart: always

    build:
      context: .
      dockerfile: services/Dockerfile

    volumes:
      - "/services/"

    ports:
      - "443:443"

    # network_mode: "host"