services:
  application:
    #env_file: "services/app.env"

    #restart: always

    build:
      context: .
      dockerfile: services/Dockerfile

    volumes:
      - "/services/"

    ports:
      - "443:5000"