services:
  # frontend:
  #   image: nginx
  #   restart: always
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - "/services/ressources/"
  #   networks:
  #   - front-tier
  #   - back-tier
  #   configs:
  #     - httpd-config
  #   secrets:
  #     - server-certificate

  application:
    #restart: always
    build:
      context: .
      dockerfile: services/Dockerfile
    volumes:
      - "/services/"
    ports:
    - "5000:5000"