services:
  web_app:
    build:
      context: .
      dockerfile: services/Dockerfile
    expose:
     - 5000

  nginx:
    build:
      context: .
      dockerfile: services/etc/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"